
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # thymeleaf以严格的html5
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
server:
  port: 80

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:  classpath:mybatis/mapper/*.xml

#日志配置
logging:
  path: D:\log
  level:
    com.blog: debug
    org:
      springframework:
        web: debug
        transaction: debug
#自定义图片保存路径
#userImages: file:D:\upload\
